name: basic_utilities_ck
description: "A temporary Flutter package for testing and experimentation.This package is created for testing and experimentation purposes only. It may contain code or features that are not intended for production use. Feel free to use it for your testing needs, and you can delete it after you're done with your testing and experimentation."
version: 0.0.3
repository: "https://github.com/ChintanK8080/basic_utilities.git"

environment:
  sdk: '>=3.0.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.2
  shared_preferences: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0




